version: "2"
services:
  php:
    image: polux/web-srv:dev
    container_name: web-srv-02
    networks:
        - my-network
    ports:
      - "80:80"
      - "9000:9000"


    volumes:
      - /home/polux/Projects/php-myged/www:/var/www/html/php-myged/
      - ./logs-apache2:/var/log/apache2/
      - ./logs-php:/var/log/php/
networks:
   my-network:
    external: true
