version: "2"
services:
  php:
    image: polux/web-srv:dev
    container_name: web-srv-02
    networks:
        - internal
    ports:
      - "8080:80"
      - "9090:9000"


    volumes:
      - /home/polux/Projects/php-myged/www:/var/www/html/php-myged/
      - ./logs-apache2:/var/log/apache2/
      - ./logs-php:/var/log/php/
networks:
   internal:
